//let selectedColours=[];
let selectedColours=["RED","BLUE"];
console.log(selectedColours);
console.log(selectedColours[0]);
selectedColours[2]="GREEN";
console.log(selectedColours);
let season=["spring","autumn","winter","summer"];
console.log(season[1].length);
selectedColours.push("black");
console.log(selectedColours);
selectedColours.unshift("black");
console.log(selectedColours);
selectedColours.shift("black");
console.log(selectedColours);
selectedColours.shift("black");
console.log(selectedColours);
selectedColours.pop();
console.log(selectedColours);
selectedColours.pop();
console.log(selectedColours.indexOf("RED"));
